[package]
name = "rjq"
version = "1.0.0"
authors = ["freestrings <freestrings@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
pest = "2.0"
pest_derive = "2.0"
pest_grammars = "2.0"

[dev-dependencies]
bencher = "0.1.5"